# Generated by Django 4.0.7 on 2022-10-26 14:30

import apps.glue
import apps.names.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('name_key', apps.glue.FixedCharField(db_column='NAME_KEY', max_length=16, primary_key=True, serialize=False)),
                ('organisation', models.BooleanField(db_column='ORGANISATION')),
                ('comment', models.TextField(blank=True, db_column='COMMENT', null=True)),
                ('entered_by', apps.glue.FixedCharField(db_column='ENTERED_BY', max_length=16)),
                ('entry_date', models.DateTimeField(db_column='ENTRY_DATE')),
                ('changed_by', apps.glue.FixedCharField(blank=True, db_column='CHANGED_BY', max_length=16, null=True)),
                ('changed_date', models.DateTimeField(blank=True, db_column='CHANGED_DATE', null=True)),
                ('system_supplied_data', models.BooleanField(db_column='SYSTEM_SUPPLIED_DATA')),
                ('custodian', apps.glue.FixedCharField(blank=True, db_column='CUSTODIAN', max_length=8, null=True)),
            ],
            options={
                'db_table': 'NAME',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name_key', models.OneToOneField(db_column='NAME_KEY', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='names.name')),
                ('password', models.CharField(db_column='PASSWORD', max_length=20)),
                ('security_level', models.SmallIntegerField(db_column='SECURITY_LEVEL')),
                ('first_login', models.BooleanField(db_column='FIRST_LOGIN')),
                ('full_edit_own_data', models.BooleanField(db_column='FULL_EDIT_OWN_DATA')),
                ('last_login', models.DateTimeField(db_column='Django_LAST_LOGIN')),
                ('username', models.CharField(db_column='Django_USERNAME', max_length=61, unique=True)),
            ],
            options={
                'db_table': 'USER',
                'managed': False,
            },
            managers=[
                ('objects', apps.names.models.R6UserManager()),
            ],
        ),
    ]
