# Generated by Django 4.0.7 on 2022-10-26 14:30

import apps.glue
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('journal_key', apps.glue.FixedCharField(db_column='JOURNAL_KEY', max_length=16, primary_key=True, serialize=False)),
                ('short_name', models.CharField(blank=True, db_column='SHORT_NAME', max_length=50, null=True)),
                ('long_name', models.CharField(blank=True, db_column='LONG_NAME', max_length=100, null=True)),
                ('description', models.TextField(blank=True, db_column='DESCRIPTION', null=True)),
                ('entered_by', apps.glue.FixedCharField(db_column='ENTERED_BY', max_length=16)),
                ('entry_date', models.DateTimeField(db_column='ENTRY_DATE')),
                ('changed_by', apps.glue.FixedCharField(blank=True, db_column='CHANGED_BY', max_length=16, null=True)),
                ('changed_date', models.DateTimeField(blank=True, db_column='CHANGED_DATE', null=True)),
                ('system_supplied_data', models.BooleanField(db_column='SYSTEM_SUPPLIED_DATA')),
                ('custodian', apps.glue.FixedCharField(blank=True, db_column='CUSTODIAN', max_length=8, null=True)),
            ],
            options={
                'db_table': 'JOURNAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenceAuthor',
            fields=[
                ('author_key', apps.glue.FixedCharField(db_column='AUTHOR_KEY', max_length=16, primary_key=True, serialize=False)),
                ('initials', apps.glue.FixedCharField(blank=True, db_column='INITIALS', max_length=8, null=True)),
                ('item_name', models.CharField(db_column='ITEM_NAME', max_length=50)),
                ('sort_order', models.SmallIntegerField(db_column='SORT_ORDER')),
                ('entered_by', apps.glue.FixedCharField(db_column='ENTERED_BY', max_length=16)),
                ('entry_date', models.DateTimeField(db_column='ENTRY_DATE')),
                ('changed_by', apps.glue.FixedCharField(blank=True, db_column='CHANGED_BY', max_length=16, null=True)),
                ('changed_date', models.DateTimeField(blank=True, db_column='CHANGED_DATE', null=True)),
                ('custodian', apps.glue.FixedCharField(blank=True, db_column='CUSTODIAN', max_length=8, null=True)),
                ('system_supplied_data', models.BooleanField(db_column='SYSTEM_SUPPLIED_DATA')),
            ],
            options={
                'db_table': 'REFERENCE_AUTHOR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenceEditor',
            fields=[
                ('editor_key', apps.glue.FixedCharField(db_column='EDITOR_KEY', max_length=16, primary_key=True, serialize=False)),
                ('initials', apps.glue.FixedCharField(blank=True, db_column='INITIALS', max_length=8, null=True)),
                ('item_name', models.CharField(db_column='ITEM_NAME', max_length=50)),
                ('sort_order', models.SmallIntegerField(db_column='SORT_ORDER')),
                ('entered_by', apps.glue.FixedCharField(db_column='ENTERED_BY', max_length=16)),
                ('entry_date', models.DateTimeField(db_column='ENTRY_DATE')),
                ('changed_by', apps.glue.FixedCharField(blank=True, db_column='CHANGED_BY', max_length=16, null=True)),
                ('changed_date', models.DateTimeField(blank=True, db_column='CHANGED_DATE', null=True)),
                ('custodian', apps.glue.FixedCharField(blank=True, db_column='CUSTODIAN', max_length=8, null=True)),
            ],
            options={
                'db_table': 'REFERENCE_EDITOR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenceNumber',
            fields=[
                ('number_key', apps.glue.FixedCharField(db_column='NUMBER_KEY', max_length=16, primary_key=True, serialize=False)),
                ('number', models.CharField(db_column='NUMBER', max_length=20)),
                ('reference_number_type', models.CharField(db_column='REFERENCE_NUMBER_TYPE', max_length=20)),
                ('entered_by', apps.glue.FixedCharField(db_column='ENTERED_BY', max_length=16)),
                ('entry_date', models.DateTimeField(db_column='ENTRY_DATE')),
                ('changed_by', apps.glue.FixedCharField(blank=True, db_column='CHANGED_BY', max_length=16, null=True)),
                ('changed_date', models.DateTimeField(blank=True, db_column='CHANGED_DATE', null=True)),
                ('custodian', apps.glue.FixedCharField(blank=True, db_column='CUSTODIAN', max_length=8, null=True)),
                ('system_supplied_data', models.BooleanField(db_column='SYSTEM_SUPPLIED_DATA')),
            ],
            options={
                'db_table': 'REFERENCE_NUMBER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_key', apps.glue.FixedCharField(db_column='SOURCE_KEY', max_length=16, primary_key=True, serialize=False)),
                ('internal', models.BooleanField(db_column='INTERNAL')),
                ('custodian', apps.glue.FixedCharField(blank=True, db_column='CUSTODIAN', max_length=8, null=True)),
            ],
            options={
                'db_table': 'SOURCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('source_key', models.OneToOneField(db_column='SOURCE_KEY', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sources.source')),
                ('year_vague_date_start', models.IntegerField(blank=True, db_column='YEAR_VAGUE_DATE_START', null=True)),
                ('year_vague_date_end', models.IntegerField(blank=True, db_column='YEAR_VAGUE_DATE_END', null=True)),
                ('year_vague_date_type', models.CharField(blank=True, db_column='YEAR_VAGUE_DATE_TYPE', max_length=2, null=True)),
                ('full_reference', models.TextField(blank=True, db_column='FULL_REFERENCE', null=True)),
                ('title', models.TextField(blank=True, db_column='TITLE', null=True)),
                ('volume', models.CharField(blank=True, db_column='VOLUME', max_length=10, null=True)),
                ('part', models.SmallIntegerField(blank=True, db_column='PART', null=True)),
                ('number', models.SmallIntegerField(blank=True, db_column='NUMBER', null=True)),
                ('pages', models.CharField(blank=True, db_column='PAGES', max_length=20, null=True)),
                ('supplement', models.CharField(blank=True, db_column='SUPPLEMENT', max_length=50, null=True)),
                ('edition', models.CharField(blank=True, db_column='EDITION', max_length=10, null=True)),
                ('symposium_title', models.CharField(blank=True, db_column='SYMPOSIUM_TITLE', max_length=50, null=True)),
                ('publisher', models.CharField(blank=True, db_column='PUBLISHER', max_length=50, null=True)),
                ('place_of_publication', models.CharField(blank=True, db_column='PLACE_OF_PUBLICATION', max_length=50, null=True)),
                ('reference_type', models.CharField(db_column='REFERENCE_TYPE', max_length=25)),
                ('original_file', models.TextField(blank=True, db_column='ORIGINAL_FILE', null=True)),
                ('entered_by', apps.glue.FixedCharField(db_column='ENTERED_BY', max_length=16)),
                ('entry_date', models.DateTimeField(db_column='ENTRY_DATE')),
                ('changed_by', apps.glue.FixedCharField(blank=True, db_column='CHANGED_BY', max_length=16, null=True)),
                ('changed_date', models.DateTimeField(blank=True, db_column='CHANGED_DATE', null=True)),
                ('system_supplied_data', models.BooleanField(db_column='SYSTEM_SUPPLIED_DATA')),
                ('physical_location', models.CharField(blank=True, db_column='PHYSICAL_LOCATION', max_length=100, null=True)),
            ],
            options={
                'db_table': 'REFERENCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('source_key', models.OneToOneField(db_column='SOURCE_KEY', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sources.source')),
                ('file_name', models.CharField(db_column='FILE_NAME', max_length=255)),
                ('title', models.CharField(blank=True, db_column='TITLE', max_length=100, null=True)),
            ],
            options={
                'db_table': 'SOURCE_FILE',
                'managed': False,
            },
        ),
    ]
