# Generated by Django 4.0.7 on 2022-10-26 14:30

import apps.glue
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminArea',
            fields=[
                ('admin_area_key', apps.glue.FixedCharField(db_column='ADMIN_AREA_KEY', max_length=16, primary_key=True, serialize=False)),
                ('item_name', models.CharField(db_column='ITEM_NAME', max_length=60)),
                ('parent', apps.glue.FixedCharField(blank=True, db_column='PARENT', max_length=16, null=True)),
                ('short_code', models.CharField(blank=True, db_column='SHORT_CODE', max_length=10, null=True)),
                ('entered_by', apps.glue.FixedCharField(db_column='ENTERED_BY', max_length=16)),
                ('entry_date', models.DateTimeField(db_column='ENTRY_DATE')),
                ('changed_by', apps.glue.FixedCharField(blank=True, db_column='CHANGED_BY', max_length=16, null=True)),
                ('changed_date', models.DateTimeField(blank=True, db_column='CHANGED_DATE', null=True)),
                ('system_supplied_data', models.BooleanField(db_column='SYSTEM_SUPPLIED_DATA')),
                ('custodian', apps.glue.FixedCharField(blank=True, db_column='CUSTODIAN', max_length=8, null=True)),
            ],
            options={
                'db_table': 'ADMIN_AREA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminAreaSources',
            fields=[
                ('source_link_key', apps.glue.FixedCharField(db_column='SOURCE_LINK_KEY', max_length=16, primary_key=True, serialize=False)),
                ('original', models.BooleanField(db_column='ORIGINAL')),
                ('custodian', apps.glue.FixedCharField(blank=True, db_column='CUSTODIAN', max_length=8, null=True)),
            ],
            options={
                'db_table': 'ADMIN_AREA_SOURCES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminBoundary',
            fields=[
                ('admin_boundary_key', apps.glue.FixedCharField(db_column='ADMIN_BOUNDARY_KEY', max_length=16, primary_key=True, serialize=False)),
                ('date_from', models.DateTimeField(blank=True, db_column='DATE_FROM', null=True)),
                ('date_to', models.DateTimeField(blank=True, db_column='DATE_TO', null=True)),
                ('object_id', models.SmallIntegerField(blank=True, db_column='OBJECT_ID', null=True)),
                ('authority', models.CharField(blank=True, db_column='AUTHORITY', max_length=50, null=True)),
                ('entered_by', apps.glue.FixedCharField(db_column='ENTERED_BY', max_length=16)),
                ('entry_date', models.DateTimeField(db_column='ENTRY_DATE')),
                ('changed_by', apps.glue.FixedCharField(blank=True, db_column='CHANGED_BY', max_length=16, null=True)),
                ('changed_date', models.DateTimeField(blank=True, db_column='CHANGED_DATE', null=True)),
                ('system_supplied_data', models.BooleanField(db_column='SYSTEM_SUPPLIED_DATA')),
                ('map_sheet_key', apps.glue.FixedCharField(blank=True, db_column='MAP_SHEET_KEY', max_length=16, null=True)),
                ('custodian', apps.glue.FixedCharField(blank=True, db_column='CUSTODIAN', max_length=8, null=True)),
            ],
            options={
                'db_table': 'ADMIN_BOUNDARY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminRelation',
            fields=[
                ('admin_relation_key', apps.glue.FixedCharField(db_column='ADMIN_RELATION_KEY', max_length=16, primary_key=True, serialize=False)),
                ('relation_1_to_2', models.CharField(blank=True, db_column='RELATION_1_TO_2', max_length=25, null=True)),
                ('relation_2_to_1', models.CharField(blank=True, db_column='RELATION_2_TO_1', max_length=25, null=True)),
                ('entered_by', apps.glue.FixedCharField(db_column='ENTERED_BY', max_length=16)),
                ('entry_date', models.DateTimeField(db_column='ENTRY_DATE')),
                ('changed_by', apps.glue.FixedCharField(blank=True, db_column='CHANGED_BY', max_length=16, null=True)),
                ('changed_date', models.DateTimeField(blank=True, db_column='CHANGED_DATE', null=True)),
                ('system_supplied_data', models.BooleanField(db_column='SYSTEM_SUPPLIED_DATA')),
                ('custodian', apps.glue.FixedCharField(blank=True, db_column='CUSTODIAN', max_length=8, null=True)),
            ],
            options={
                'db_table': 'ADMIN_RELATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminType',
            fields=[
                ('admin_type_key', apps.glue.FixedCharField(db_column='ADMIN_TYPE_KEY', max_length=16, primary_key=True, serialize=False)),
                ('short_name', models.CharField(db_column='SHORT_NAME', max_length=50)),
                ('long_name', models.CharField(blank=True, db_column='LONG_NAME', max_length=100, null=True)),
                ('description', models.TextField(blank=True, db_column='DESCRIPTION', null=True)),
                ('authority', models.CharField(blank=True, db_column='AUTHORITY', max_length=100, null=True)),
                ('date_from', models.DateTimeField(blank=True, db_column='DATE_FROM', null=True)),
                ('date_to', models.DateTimeField(blank=True, db_column='DATE_TO', null=True)),
                ('entered_by', apps.glue.FixedCharField(db_column='ENTERED_BY', max_length=16)),
                ('entry_date', models.DateTimeField(db_column='ENTRY_DATE')),
                ('changed_by', apps.glue.FixedCharField(blank=True, db_column='CHANGED_BY', max_length=16, null=True)),
                ('changed_date', models.DateTimeField(blank=True, db_column='CHANGED_DATE', null=True)),
                ('system_supplied_data', models.BooleanField(db_column='SYSTEM_SUPPLIED_DATA')),
                ('custodian', apps.glue.FixedCharField(blank=True, db_column='CUSTODIAN', max_length=8, null=True)),
            ],
            options={
                'db_table': 'ADMIN_TYPE',
                'managed': False,
            },
        ),
    ]
